### ISSUE TITLE
errors on initial run

### ISSUE THREAD

**Issue by gunnard** [johannesthyssen/vim-signit#2]
Fresh install with vundle
1)added initials
2)added name
3) added link
4) hit enter on 2nd link
2. Link/Description: Error detected while processing function signit#execute[51]..<SNR>83_PrintHeader:
line    2:
E15: Invalid expression: . s:signit_ascii_spacing_tmp .. " " .. toupper(s:signit_initials_tmp)), {_, v -> printf(&cms, "    " .. v .. "    DELRN")}))
E116: Invalid arguments for function systemlist("figlet " .. s:signit_ascii_spacing_tmp .. " " .. toupper(s:signit_initials_tmp)), {_, v -> printf(&cms, "    " .. v
.. "    DELRN")}))
E116: Invalid arguments for function map(systemlist("figlet " .. s:signit_ascii_spacing_tmp .. " " .. toupper(s:signit_initials_tmp)), {_, v -> printf(&cms, "    " .
. v .. "    DELRN")}))
E116: Invalid arguments for function append

**Comment by johannesthyssen** [comment]
Can't reproduce the error. Just installed it with Vundle and ran it with Vim (version 8.2.814) and it works as expected. 
Could you provide me with some more details? e.g. What was your input in the prompts? Vim version?

**Comment by johannesthyssen** [comment]
@gunnard I finally had the time to check this issue and I found the problem. Files without a filetype had the vim option &commenstring set to nothing. This was conflicting with the printf function. The latest commits should have solved this issue :D
